# Generated by Django 3.0.5 on 2020-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinentry',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
