# Generated by Django 3.0.5 on 2020-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0002_auto_20200609_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoinentry',
            old_name='date',
            new_name='utc',
        ),
        migrations.AddField(
            model_name='bitcoinentry',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time'),
        ),
    ]
