# Generated by Django 3.0.5 on 2020-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0003_auto_20200612_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinentry',
            name='date_added',
            field=models.DateTimeField(default=' ', verbose_name='Date and Time'),
        ),
    ]
