# Generated by Django 3.0.5 on 2020-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0004_auto_20200612_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoinentry',
            name='date_added',
        ),
        migrations.AddField(
            model_name='bitcoinentry',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
